default_language_version:
  python: python3.13
repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
